### PR TITLE
QEP-57: Support file directory

### PR DESCRIPTION
**Pull request by nrccua-bradb**
https://nrccua.atlassian.net/browse/QEP-57
* Add support for passing an alternate directory of PDF files.
* Add support for direct pass-in of org FICE

### CODE REVIEW

**Comment by nrccua-kathrynr** [comment]
Let's pull out the prod stuff for now until we get more clarity.

**Comment by nrccua-bradb** [comment]
@nrccua-kathrynr Went ahead and pulled that out!

**Comment by nrccua-kathrynr** [comment]
Looked good to me - don't know if you want to have someone else review what the feature does

**Review by nrccua-kathrynr — APPROVED** [review]
I don't know if you want to have someone else review the features, but it looks good to me.

**Pull request merged**
